/**
 * Notification helper — creates a row and pushes it over WebSocket.
 * Messages are only ever generated by server-side events (verified deposits,
 * validated watch rewards, payout status changes), never by the client.
 */
const { Table } = require('../db');
const ws = require('../lib/ws');

const notifications = new Table('notifications');

/**
 * @param {number} userId
 * @param {{title:string, message:string, type?:'info'|'success'|'warning'|'danger', link?:string}} payload
 */
async function push(userId, { title, message, type = 'info', link = null }) {
  const row = await notifications.create({
    user_id: userId != null ? Number(userId) : null,
    title: String(title).slice(0, 160),
    message: String(message).slice(0, 2000),
    type,
    is_read: false,
    link,
  });
  if (userId != null) ws.sendToUser(userId, { type: 'notification', payload: row });
  return row;
}

module.exports = { push };
