-- ============================================================================
-- TaskCash Pro — reset a database that holds an INCOMPATIBLE earlier schema
--
-- WHY THIS EXISTS
--
-- A project may already contain an earlier generation of the TaskCash Pro
-- schema: the same table names with different columns, different setting keys
-- and function signatures under different parameter names. The migrations in
-- supabase/migrations/ CANNOT repair that state, because
-- `create table if not exists` silently skips a table that already exists — the
-- old columns survive, and every later migration then fails on a column that
-- was never added.
--
-- Tell-tale signs (checked by `npm run verify:remote`):
--   * `profiles` has no `auth_user_id` column
--   * `public.rate_limit_hit` exists but rejects p_bucket/p_identifier
--   * system_settings holds keys like `minimum_withdrawal` instead of the
--     dotted keys the application reads (`withdrawals.minimum_amount`)
--
-- WHAT IT DOES
--
--  1. REFUSES to run at all if any TaskCash Pro table holds a single row, or if
--     any Supabase auth account exists. A populated database must be migrated
--     deliberately, never reset.
--  2. Drops the stale functions by name, so any signature or overload goes.
--  3. Drops the TaskCash Pro tables (cascade). Tables outside that list are
--     left untouched.
--  4. Leaves everything else alone — no other schema is affected.
--
-- WHAT TO DO AFTER
--
--   npm run db:bundle     # regenerate supabase/apply-all.sql
--   -- paste that file into the SQL editor and Run --
--   npm run verify:remote
--
-- Do NOT run this on a database that holds real money records. The guard makes
-- that refusal automatic, but read it anyway.
-- ============================================================================

/* -------------------------------------------------------------------------- */
/* 1. Safety guard — no data, no accounts                                     */
/* -------------------------------------------------------------------------- */

do $$
declare
  t text;
  rows_here bigint;
  accounts bigint;
  targets text[] := array[
    'profiles', 'wallets', 'wallet_transactions', 'deposits', 'withdrawals',
    'videos', 'video_campaigns', 'video_watch_sessions', 'referrals',
    'referral_commissions', 'notifications', 'audit_logs', 'fraud_events',
    'system_settings', 'currencies', 'idempotency_keys', 'payment_events',
    'rate_limits', 'reconciliation_alerts'
  ];
  -- Configuration tables. Rows here are seed values regenerated by
  -- 0005_seed_settings.sql, not user data, so they must NOT block a reset —
  -- an unapplied project that has only ever been seeded would otherwise be
  -- impossible to reinitialise without hand-editing this script.
  seeded text[] := array['system_settings', 'currencies'];
begin
  if to_regclass('auth.users') is not null then
    execute 'select count(*) from auth.users' into accounts;
    if accounts > 0 then
      raise exception using
        message = format('REFUSING TO RESET: auth.users holds %s account(s).', accounts),
        hint = 'This script deletes the TaskCash Pro schema. It is only safe on a project with no accounts.';
    end if;
  end if;

  foreach t in array targets loop
    if to_regclass('public.' || t) is not null then
      execute format('select count(*) from public.%I', t) into rows_here;
      if rows_here > 0 and t <> all (seeded) then
        raise exception using
          message = format('REFUSING TO RESET: public.%s holds %s row(s).', t, rows_here),
          hint = 'Export or clear that data first, or reconcile the schema by hand.';
      end if;
    end if;
  end loop;

  raise notice 'Guard passed: no accounts and no user rows in any TaskCash Pro table (seed/config rows are ignored).';
end $$;

/* -------------------------------------------------------------------------- */
/* 2. Drop stale functions, whatever their signatures                          */
/* -------------------------------------------------------------------------- */

do $$
declare
  r record;
  dropped int := 0;
  stale text[] := array[
    'admin_adjust_wallet', 'block_ledger_mutation', 'campaign_is_payable',
    'claim_idempotency_key', 'current_profile_id', 'deposit_credit',
    'deposit_fail', 'ensure_profile', 'generate_referral_code',
    'handle_new_user', 'handle_user_email_confirmed', 'is_admin',
    'notify_user', 'rate_limit_hit', 'record_fraud_event',
    'referral_commission_on_deposit', 'referral_credit', 'referral_qualify',
    'setting_bool', 'setting_json', 'setting_num', 'setting_text',
    'touch_updated_at', 'video_complete_session', 'video_progress',
    'video_start', 'wallet_post', 'withdrawal_complete',
    'withdrawal_release', 'withdrawal_reserve', 'write_audit'
  ];
begin
  for r in
    select p.oid::regprocedure as signature
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = any (stale)
  loop
    execute format('drop function if exists %s cascade', r.signature);
    dropped := dropped + 1;
  end loop;

  raise notice 'Dropped % stale function(s).', dropped;
end $$;

/* -------------------------------------------------------------------------- */
/* 3. Drop triggers this project put on auth.users                             */
/* -------------------------------------------------------------------------- */

-- Scoped to triggers whose function lives in `public`, so a trigger belonging
-- to some other application sharing the auth schema is not touched.
do $$
declare
  r record;
  dropped int := 0;
begin
  if to_regclass('auth.users') is not null then
    for r in
      select t.tgname
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace cn on cn.oid = c.relnamespace
      join pg_proc p on p.oid = t.tgfoid
      join pg_namespace pn on pn.oid = p.pronamespace
      where cn.nspname = 'auth'
        and c.relname = 'users'
        and not t.tgisinternal
        and pn.nspname = 'public'
        and p.proname = any (array['handle_new_user', 'handle_user_email_confirmed'])
    loop
      execute format('drop trigger if exists %I on auth.users', r.tgname);
      dropped := dropped + 1;
    end loop;

    raise notice 'Dropped % auth.users trigger(s).', dropped;
  end if;
end $$;

/* -------------------------------------------------------------------------- */
/* 4. Drop the TaskCash Pro tables                                             */
/* -------------------------------------------------------------------------- */

-- Ordered children-first so the intent is readable; `cascade` settles any
-- remaining dependency either way.
drop table if exists public.reconciliation_alerts cascade;
drop table if exists public.payment_events cascade;
drop table if exists public.idempotency_keys cascade;
drop table if exists public.rate_limits cascade;
drop table if exists public.audit_logs cascade;
drop table if exists public.fraud_events cascade;
drop table if exists public.notifications cascade;
drop table if exists public.referral_commissions cascade;
drop table if exists public.referrals cascade;
drop table if exists public.video_watch_sessions cascade;
drop table if exists public.videos cascade;
drop table if exists public.video_campaigns cascade;
drop table if exists public.withdrawals cascade;
drop table if exists public.deposits cascade;
drop table if exists public.wallet_transactions cascade;
drop table if exists public.wallets cascade;
drop table if exists public.profiles cascade;
drop table if exists public.system_settings cascade;
drop table if exists public.currencies cascade;
drop table if exists public.taskcash_migrations cascade;

do $$
begin
  raise notice 'TaskCash Pro schema reset. Next: apply supabase/apply-all.sql, then run npm run verify:remote.';
end $$;
